### ISSUE TITLE
successrate.sh not working when executed in a crontab

### ISSUE THREAD

**Issue by stefanofornari** [ReneSmeekes/storj_success_rate#10]
hello, I run the script in a crontab, but although regularly executed, it does not provide the correct values. running the script on the same file from the same user works. see attachments
[succussrate_ok.txt](https://github.com/ReneSmeekes/storj_success_rate/files/7740907/succussrate_ok.txt)
[succussrate_ko.txt](https://github.com/ReneSmeekes/storj_success_rate/files/7740908/succussrate_ko.txt)
.

**Comment by ReneSmeekes** [comment]
Can you show me how you are running the script manually and what the crontab line is?

**Comment by stefanofornari** [comment]
something like this:
0 1 * * *       storj   /opt/STORJ/bin/successrate.sh $(ls -1 -r /opt/STORJ/logs/storagenode.*|head -1) > /opt/STORJ/logs/successrate.txt

I am debugging it and it is the printf...

**Comment by stefanofornari** [comment]
see PR #11

**Comment by ReneSmeekes** [comment]
Merged, thanks for the suggestion!
