### ISSUE TITLE
ratio of upload success is taking put_failed into consideration twice (instead of once)

### ISSUE THREAD

**Issue by bjoerrrn** [ReneSmeekes/storj_success_rate#12]
hi there,

ratio of upload success is taking put_failed into consideration twice: 

```
#Ratio of Success
if [ $(($put_success+$put_failed+$put_canceled+$put_failed)) -ge 1 ]
```

Should be: 

```
#Ratio of Success
if [ $(($put_success+$put_canceled+$put_failed)) -ge 1 ]
```

**Comment by ReneSmeekes** [comment]
Thanks for pointing that out @dusselmann ! It should actually have been put_rejected, instead of being removed. It's now fixed in https://github.com/ReneSmeekes/storj_success_rate/commit/2f0fba090c14d935100fec984a0f59f2fa6b361c

**Comment by bjoerrrn** [comment]
Thx, was not sure yesterday - too tired. ;-)
